level_0 = {'terrain':'0/level_0_terrain.csv',
           'tree': '0/level_0_tree.csv',
           'bound':'0/level_0_boundarie.csv',
           'crate': '0/level_0_crate.csv',
           'fly_eye': '0/level_0_fly_eye.csv',
           'slime': '0/level_0_slime.csv',
           'player': '0/level_0_player.csv',
           'willow': '0/level_0_willow.csv',
           'stone': '0/level_0_stone.csv',
           'bush':'0/level_0_bush.csv',
           'ladder': '0/level_0_ladder.csv',
           'crab': '0/level_0_crab.csv',
           'fire': '0/level_0_fire.csv',
           'portal': '0/level_0_portal.csv',
           'saw': '0/level_0_saw.csv',
           'move_saw':'0/level_0_move_saw.csv',
           'banana':'0/level_0_banana.csv',
           'elevator': '0/level_0_elevator.csv',
           'flag': '0/level_0_flag.csv',
           'spike': '0/level_0_spike.csv',
           'ridge':'0/level_0_ridge.csv',
           'chest': '0/level_0_chest.csv',
           'box':'0/level_0_box.csv',
           'pointer':'0/level_0_pointer.csv'}

level_1 = {'terrain':'1/level_1_terrain.csv',
           'tree': '1/level_1_tree.csv',
           'bound':'1/level_1_boundarie.csv',
           'crate': '1/level_1_crate.csv',
           'fly_eye': '1/level_1_fly_eye.csv',
           'slime': '1/level_1_slime.csv',
           'player': '1/level_1_player.csv',
           'willow': '1/level_1_willow.csv',
           'stone': '1/level_1_stone.csv',
           'bush':'1/level_1_bush.csv',
           'crab': '1/level_1_crab.csv',
           'fire': '1/level_1_fire.csv',
           'portal': '1/level_1_portal.csv',
           'saw': '1/level_1_saw.csv',
           'move_saw':'1/level_1_move_saw.csv',
           'banana':'1/level_1_banana.csv',
           'elevator': '1/level_1_elevator.csv',
           'flag': '1/level_1_flag.csv',
           'spike':'1/level_1_spike.csv',
           'ridge':'1/level_1_ridge.csv',
           'chest':'1/level_1_chest.csv',
           'box':'1/level_1_box.csv',
           'pointer':'1/level_1_pointer.csv'}

level_2 = {'terrain':'2/level_2_terrain.csv',
           'tree': '2/level_2_tree.csv',
           'bound':'2/level_2_boundarie.csv',
           'crate': '2/level_2_crate.csv',
           'fly_eye': '2/level_2_fly_eye.csv',
           'slime': '2/level_2_slime.csv',
           'player': '2/level_2_player.csv',
           'willow': '2/level_2_willow.csv',
           'stone': '2/level_2_stone.csv',
           'bush':'2/level_2_bush.csv',
           'saw': '2/level_2_saw.csv',
           'crab': '2/level_2_crab.csv',
           'portal': '2/level_2_portal.csv',
           'fire': '2/level_2_fire.csv',
           'move_saw':'2/level_2_move_saw.csv',
           'banana':'2/level_2_banana.csv',
           'elevator': '2/level_2_elevator.csv',
           'flag': '2/level_2_flag.csv',
           'spike': '2/level_2_spike.csv',
           'ridge':'2/level_2_ridge.csv',
           'chest': '2/level_2_chest.csv',
           'box': '2/level_2_box.csv',
           'pointer': '2/level_2_pointer.csv'}
