level_0 = {'terrain':'0/level_0_terrain.csv',
           'tree': '0/level_0_tree.csv',
           'bound':'0/level_0_boundarie.csv',
           'crate': '0/level_0_crate.csv',
           'fly_eye': '0/level_0_fly_eye.csv',
           'slime': '0/level_0_slime.csv',
           'player': '0/level_0_player.csv',
           'willow': '0/level_0_willow.csv',
           'stone': '0/level_0_stone.csv',
           'bush':'0/level_0_bush.csv',
           'ladder': '0/level_0_ladder.csv'}

level_1 = {'terrain':'0/level_0_terrain.csv',
           'tree': '0/level_0_tree.csv',
           'bound':'0/level_0_boundarie.csv',
           'crate': '0/level_0_crate.csv',
           'fly_eye': '0/level_0_fly_eye.csv',
           'slime': '0/level_0_slime.csv',
           'player': '0/level_0_player.csv',
           'willow': '0/level_0_willow.csv',
           'stone': '0/level_0_stone.csv',
           'bush':'0/level_0_bush.csv',
           'ladder': '0/level_0_ladder.csv'}