level_0 = {'terrain':'0/level_0_terrain.csv',
           'tree': '0/level_0_tree.csv',
           'bound':'0/level_0_boundarie.csv',
           'crate': '0/level_0_crate.csv',
           'fly_eye': '0/level_0_fly_eye.csv',
           'slime': '0/level_0_slime.csv',
           'player': '0/level_0_player.csv',
           'willow': '0/level_0_willow.csv',
           'stone': '0/level_0_stone.csv',
           'bush':'0/level_0_bush.csv',
           'ladder': '0/level_0_ladder.csv',
           'crab': '0/level_0_crab.csv',
           'fire': '0/level_0_fire.csv'}

level_1 = {'terrain':'1/level_1_terrain.csv',
           'tree': '1/level_1_tree.csv',
           'bound':'1/level_1_boundarie.csv',
           'crate': '1/level_1_crate.csv',
           'fly_eye': '1/level_1_fly_eye.csv',
           'slime': '1/level_1_slime.csv',
           'player': '1/level_1_player.csv',
           'willow': '1/level_1_willow.csv',
           'stone': '1/level_1_stone.csv',
            'bush':'1/level_1_bush.csv'}

level_2 = {'terrain':'2/level_2_terrain.csv',
           'tree': '2/level_2_tree.csv',
           'bound':'2/level_2_boundarie.csv',
           'crate': '2/level_2_crate.csv',
           'fly_eye': '2/level_2_fly_eye.csv',
           'slime': '2/level_2_slime.csv',
           'player': '2/level_2_player.csv',
           'willow': '2/level_2_willow.csv',
           'stone': '2/level_2_stone.csv',
            'bush':'2/level_2_bush.csv'}
